### ISSUE TITLE
Help about start.sh

### ISSUE THREAD

**Issue by a-laborie** [eszabo12/image_capturing_pipeline#1]
Hello, 
Thank you for your work. We are currently trying to use your software to control our Intel realsense2 camera. I had a stupid question: I don't find any start.sh file in the folder so I cannot execute it. Has it to be generated before? 
Btw I am using Ubuntu 20.04.
Thank you and best regards, 
Alexandre Laborie

**Comment by ryo-matsuzaka** [comment]
@a-laborie 
You should run Makefile.

**Comment by elleszabo** [comment]
Hi @a-laborie, not a stupid question. Sorry I didn't see this issue until now. I updated the readme with the correct instructions as per @ryo-matsuzaka 's comment. Thanks for checking it out, would love to hear the projects you used it for.

**Comment by a-laborie** [comment]
Thank you for your answer. We were using the realsense2 camera mounted on a robotic arm OpenManipulator from the korean company ROBOTIS to take pictures of labelled objects (handwritten numbers). Then a small neural network was used to sort the objects according to the labels.

**Comment by elleszabo** [comment]
Very cool
